config/routes.rb
Rails.application.routes.draw do
  resources :election_protocols
  resources :candidate_lists
  resources :ballot_boxes
  resources :ballot_papers
  resources :candidates
  resources :elections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'
  
  post '/candidate_lists/:id/submit_candidacy', to: 'candidate_lists#submit_candidacy'
  delete '/candidate_lists/:id/destroy_candidacy/:candidate_id', to: 'candidate_lists#destroy_candidacy'

  get 'elections/:id/count_votes', to: 'elections#count_votes'
  post 'elections/:id/count_votes', to: 'elections#count_votes'

end

app/models/election_protocol.rb
class ElectionProtocol
  include Mongoid::Document
  belongs_to :election
  field :results, type: Hash
end

app/controllers/election_protocols_controller.rb
class ElectionProtocolsController < ApplicationController
  before_action :set_election_protocol, only: [:show, :edit, :update, :destroy]

  # GET /election_protocols
  # GET /election_protocols.json
  def index
    @election_protocols = ElectionProtocol.all
  end

  # GET /election_protocols/1
  # GET /election_protocols/1.json
  def show
  end

  # GET /election_protocols/new
  def new
    @election_protocol = ElectionProtocol.new
  end

  # GET /election_protocols/1/edit
  def edit
  end

  # POST /election_protocols
  # POST /election_protocols.json
  def create
    @election_protocol = ElectionProtocol.new(election_protocol_params)

    respond_to do |format|
      if @election_protocol.save
        format.html { redirect_to @election_protocol, notice: 'Election protocol was successfully created.' }
        format.json { render :show, status: :created, location: @election_protocol }
      else
        format.html { render :new }
        format.json { render json: @election_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /election_protocols/1
  # PATCH/PUT /election_protocols/1.json
  def update
    respond_to do |format|
      if @election_protocol.update(election_protocol_params)
        format.html { redirect_to @election_protocol, notice: 'Election protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @election_protocol }
      else
        format.html { render :edit }
        format.json { render json: @election_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /election_protocols/1
  # DELETE /election_protocols/1.json
  def destroy
    @election_protocol.destroy
    respond_to do |format|
      format.html { redirect_to election_protocols_url, notice: 'Election protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election_protocol
      @election_protocol = ElectionProtocol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def election_protocol_params
      params.fetch(:election_protocol, {})
    end
end

app/helpers/election_protocols_helper.rb
module ElectionProtocolsHelper
end

app/views/election_protocols/_form.html.erb
<%= form_for(election_protocol) do |f| %>
  <% if election_protocol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(election_protocol.errors.count, "error") %> prohibited this election_protocol from being saved:</h2>

      <ul>
      <% election_protocol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/election_protocols/edit.html.erb
<h1>Editing Election Protocol</h1>

<%= render 'form', election_protocol: @election_protocol %>

<%= link_to 'Show', @election_protocol %> |
<%= link_to 'Back', election_protocols_path %>

app/views/election_protocols/index.html.erb
<h1>Election Protocols</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @election_protocols.each do |election_protocol| %>
      <tr>
        <td><%= link_to 'Show', election_protocol %></td>
        <td><%= link_to 'Edit', edit_election_protocol_path(election_protocol) %></td>
        <td><%= link_to 'Destroy', election_protocol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Election Protocol', new_election_protocol_path %>

app/views/election_protocols/new.html.erb
<h1>New Election Protocol</h1>

<%= render 'form', election_protocol: @election_protocol %>

<%= link_to 'Back', election_protocols_path %>

app/views/election_protocols/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Volební výsledky - <%= @election_protocol.election.title %></h1>
<% if @election_protocol.election.state != 'votes_counted' then %>
    <div class="alert alert-warning">
        Volby ještě nebyly vyhodnoceny
    </div>
<% else %>
    <strong>Typ:</strong><%=t "election_type.#{@election_protocol.election.election_type}" %><br>
    <strong>Působnost:</strong> <%= election_scope_name(@election_protocol.election) %><br>
    <strong>Hlasování:</strong> od <%= format_date @election_protocol.election.voting_starts_at %> do <%= format_date @election_protocol.election.voting_ends_at %><br>
    <h2>Výsledky</h2>
    <% if @election_protocol.election.election_type == 'resolution' %>
        <table class="table table-striped table-hover">
            <tr>
                <th>PRO</th>
                <th>PROTI</th>
            </tr>
            <tr>
                <% votes = @election_protocol.results['resolution'] %>
                <td>
                    <strong>Počet hlasů:</strong> <%= votes[:for].length %><br>
                    <strong>Hlasy:</strong>
                    <% votes[:for].each do |vote_hash| %>
                        <pre><%= vote_hash %></pre>
                    <% end %>
                </td>
                <td>
                    <strong>Počet hlasů:</strong> <%= votes[:against].length %><br>
                    <strong>Hlasy:</strong>
                    <% votes[:against].each do |vote_hash| %>
                        <pre><%= vote_hash %></pre>
                    <% end %>
                </td>
            </tr>
        </table>
    <% else %>
        <table class="table table-striped table-hover">
            <tr>
                <th>kandidát</th>
                <th>PRO</th>
                <th>PROTI</th>
            </tr>
            <% @election_protocol.results.each do |candidate_id, votes| %>
                <tr>
                    <td><%= @election_protocol.election.candidate_list.candidates.find(candidate_id).full_name %></td>
                    <td>
                        <strong>Počet hlasů:</strong> <%= votes[:for].length %><br>
                        <strong>Hlasy:</strong>
                        <% votes[:for].each do |vote_hash| %>
                            <pre><%= vote_hash %></pre>
                        <% end %>
                    </td>
                    <td>
                        <strong>Počet hlasů:</strong> <%= votes[:against].length %><br>
                        <strong>Hlasy:</strong>
                        <% votes[:against].each do |vote_hash| %>
                            <pre><%= vote_hash %></pre>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    <% end %>
<% end %>