config/routes.rb
Rails.application.routes.draw do
  resources :election_protocols
  resources :candidate_lists
  resources :ballot_boxes
  resources :ballot_papers
  resources :candidates
  resources :elections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'
  
  post '/candidate_lists/:id/submit_candidacy', to: 'candidate_lists#submit_candidacy'
  delete '/candidate_lists/:id/destroy_candidacy/:candidate_id', to: 'candidate_lists#destroy_candidacy'

  get 'elections/:id/count_votes', to: 'elections#count_votes'
  post 'elections/:id/count_votes', to: 'elections#count_votes'

end

app/models/ballot_box.rb
class BallotBox
  include Mongoid::Document
  belongs_to :election
  embeds_many :ballot_papers
end

app/controllers/ballot_boxes_controller.rb
class BallotBoxesController < ApplicationController
  before_action :set_ballot_box, only: [:show]

  # GET /ballot_boxes
  # GET /ballot_boxes.json
  #def index
  #  @ballot_boxes = BallotBox.all
  #end

  # GET /ballot_boxes/1
  # GET /ballot_boxes/1.json
  def show
    @ballot_papers = @ballot_box.ballot_papers
  end

  # GET /ballot_boxes/new
  #def new
  #  @ballot_box = BallotBox.new
  #end

  # GET /ballot_boxes/1/edit
  #def edit
  #end

  # POST /ballot_boxes
  # POST /ballot_boxes.json
  #def create
  #  @ballot_box = BallotBox.new(ballot_box_params)
  #
  # respond_to do |format|
  #    if @ballot_box.save
  #      format.html { redirect_to @ballot_box, notice: 'Ballot box was successfully created.' }
  #      format.json { render :show, status: :created, location: @ballot_box }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @ballot_box.errors, status: :unprocessable_entity }
  ##    end
  #  end
  #end

  # PATCH/PUT /ballot_boxes/1
  # PATCH/PUT /ballot_boxes/1.json
  #def update
  #  respond_to do |format|
  #    if @ballot_box.update(ballot_box_params)
  #      format.html { redirect_to @ballot_box, notice: 'Ballot box was successfully updated.' }
  ##      format.json { render :show, status: :ok, location: @ballot_box }
  #   else
  #      format.html { render :edit }
  #      format.json { render json: @ballot_box.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /ballot_boxes/1
  # DELETE /ballot_boxes/1.json
  #def destroy
  #  @ballot_box.destroy
  #  respond_to do |format|
  #    format.html { redirect_to ballot_boxes_url, notice: 'Ballot box was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ballot_box
      @ballot_box = BallotBox.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballot_box_params
      params.fetch(:ballot_box, {})
    end
end

app/helpers/ballot_box_helper.rb
module BallotBoxHelper
end

app/helpers/ballot_boxes_helper.rb
module BallotBoxesHelper
end

app/views/ballot_boxes/_form.html.erb
<%= form_for(ballot_box) do |f| %>
  <% if ballot_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_box.errors.count, "error") %> prohibited this ballot_box from being saved:</h2>

      <ul>
      <% ballot_box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballot_boxes/edit.html.erb
<h1>Editing Ballot Box</h1>

<%= render 'form', ballot_box: @ballot_box %>

<%= link_to 'Show', @ballot_box %> |
<%= link_to 'Back', ballot_boxes_path %>

app/views/ballot_boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ballot Boxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ballot_boxes.each do |ballot_box| %>
      <tr>
        <td><%= link_to 'Show', ballot_box %></td>
        <td><%= link_to 'Edit', edit_ballot_box_path(ballot_box) %></td>
        <td><%= link_to 'Destroy', ballot_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ballot Box', new_ballot_box_path %>

app/views/ballot_boxes/new.html.erb
<h1>New Ballot Box</h1>

<%= render 'form', ballot_box: @ballot_box %>

<%= link_to 'Back', ballot_boxes_path %>

app/views/ballot_boxes/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Kontrolní součty zašifrovaných hlasů ve velební urně voleb <%= @ballot_box.election.title %></th>
    </tr>
  </thead>

  <tbody>
    <% @ballot_papers.each do |ballot_paper| %>
      <tr>
        <td><%= ballot_paper.encrypted_vote_hash %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'Edit', edit_ballot_box_path(@ballot_box) %> |
<%= link_to 'Back', ballot_boxes_path %>