config/routes.rb
Rails.application.routes.draw do
  resources :election_protocols
  resources :candidate_lists
  resources :ballot_boxes
  resources :ballot_papers
  resources :candidates
  resources :elections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'
  
  post '/candidate_lists/:id/submit_candidacy', to: 'candidate_lists#submit_candidacy'
  delete '/candidate_lists/:id/destroy_candidacy/:candidate_id', to: 'candidate_lists#destroy_candidacy'

  get 'elections/:id/count_votes', to: 'elections#count_votes'
  post 'elections/:id/count_votes', to: 'elections#count_votes'

end

app/models/ballot_paper.rb
class BallotPaper
  include Mongoid::Document
  field :encrypted_vote, type: String
  field :vote_hash, type: String
  field :encrypted_vote_hash, type: String
  embedded_in :ballot_box
  
  validates :encrypted_vote, presence: true, allow_blank: false
  validates :vote_hash, presence: true, allow_blank: false
  validates :encrypted_vote_hash, presence: true, allow_blank: false

end

app/controllers/ballot_papers_controller.rb
class BallotPapersController < ApplicationController
  
  require 'encryption'
  require "base64"
  before_action :set_ballot_paper, only: [:show, :edit, :update, :destroy]
  before_action :set_election, only: [:new, :create]

  # # GET /ballot_papers
  # # GET /ballot_papers.json
  # def index
  #   @ballot_papers = BallotPaper.all
  # end

  # GET /ballot_papers/1
  # GET /ballot_papers/1.json
  def show
  end

  # GET /ballot_papers/new
  def new
    @ballot_paper = BallotPaper.new
  end

  # # GET /ballot_papers/1/edit
  # def edit
  # end

  # POST /ballot_papers
  # POST /ballot_papers.json

  #vytvoreni, zasifrovani a ulozeni hlasu
  def create
    @ballot_paper = BallotPaper.new(ballot_box: @election.ballot_box)
    authorize! :create, @ballot_paper

    saved = false
    if !@election.is_voting_phase? then
      flash[:error] = 'Nemůžete hlasovat'
    elsif @election.participant_list.has_voted?(current_user['id']) then
      flash[:error] = 'V těchto volbách jste již hlasoval'
    else
      choices = params[:choices]
      salt = SecureRandom.hex(64)
      salted_vote = {choices: choices, salt: salt}
      @ballot_paper.vote_hash = hash_of_data(salted_vote)
      vote = {choices: choices, vote_hash: @ballot_paper.vote_hash, salt: salt}
      public_key = Encryption::PublicKey.new(@election.public_key)
      @ballot_paper.encrypted_vote = Base64.encode64(public_key.encrypt(vote.to_json))
      @ballot_paper.encrypted_vote_hash = hash_of_data(@ballot_paper.encrypted_vote)    
      ballot_box = @election.ballot_box
      #ballot_box.ballot_papers.build(:encrypted_vote=> @ballot_paper.encrypted_vote, :vote_hash => @ballot_paper.vote_hash, :encrypted_vote_hash => @ballot_paper.encrypted_vote_hash )
      @election.participant_list.add_voter(current_user['id'])
      saved = ballot_box.save && @election.participant_list.save
      #if saved then BallotPaperMailer.ballot_paper_mail(@election, @ballot_paper, current_user).deliver #### Odkomentovat pro pouzivani maileru
    end

    respond_to do |format|
      if saved
        format.html { redirect_to "/elections/?state=voting" , notice: 'Váš hlas byl uspěšně vložen do volební urny.' }
        format.json { render :show, status: :created, location: @ballot_paper }
      else
        format.html { render :new }
        format.json { render json: @ballot_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /ballot_papers/1
  # # PATCH/PUT /ballot_papers/1.json
  # def update
  #   respond_to do |format|
  #     if @ballot_paper.update(ballot_paper_params)
  #       format.html { redirect_to @ballot_paper, notice: 'Ballot paper was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @ballot_paper }
  #     else
  #       format.html { renedr :edit }
  #       format.json { render json: @ballot_paper.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /ballot_papers/1
  # # DELETE /ballot_papers/1.json
  # def destroy
  #   @ballot_paper.destroy
  #   respond_to do |format|
  #     format.html { redirect_to ballot_papers_url, notice: 'Ballot paper was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ballot_paper
      @ballot_paper = BallotPaper.find(params[:id])
    end

    def hash_of_data_with_salt(data)
       Digest::SHA2.new(512).hexdigest(data.to_s + SecureRandom.hex(64))
    end

    def hash_of_data(data)
       Digest::SHA2.new(512).hexdigest(data.to_s)
    end

    def set_election
      @election = Election.find(params[:election])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballot_paper_params
      params.permit(:election, :choices)
    end
end

app/helpers/ballot_papers_helper.rb
module BallotPapersHelper
end

app/views/ballot_papers/_candidates_approval_form.html.erb
<%= form_for(ballot_paper) do |f| %>
  <% if ballot_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_paper.errors.count, "error") %> prohibited this ballot_paper from being saved:</h2>

      <ul>
      <% ballot_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Kandidát</th>
        <th>Hlasujete PRO/PROTI kandidátovi ?</th>
      </tr>
    </thead>

    <tbody>
      <% @election.candidate_list.candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.full_name %></td>
          <td><%= radio_button_tag "choices[#{candidate.id}]", "for" %> PRO</td>
          <td><%= radio_button_tag "choices[#{candidate.id}]", "against", true %> PROTI</td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3">
          <%= hidden_field_tag "election", @election.id %>
          <%= link_to 'Hlasovat v jiných volbách', elections_path(state: :voting), {:class => 'btn btn-link pull-left'} %>
          <%= f.submit "Hlasovat", {:class => 'btn btn-primary pull-right'} %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/ballot_papers/_candidates_choosing_form.html.erb
<%= form_for(ballot_paper) do |f| %>
  <% if ballot_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_paper.errors.count, "error") %> prohibited this ballot_paper from being saved:</h2>

      <ul>
      <% ballot_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Počet udělitelných hlasů:</strong>
     <%= @election.eligible_seats %>
  </p>
  
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Kandidát</th>
        <th>Hlasujete PRO kandidáty ?</th>
      </tr>
    </thead>

    <tbody>
      <% @election.candidate_list.candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.full_name %></td>
          <td><%= check_box_tag "choices[#{candidate.id}]", "for" %></td>
        </tr>
      <% end %>
      <tr>
      <%= @election.id %>
        <td colspan="3">
          <%= hidden_field_tag "election", @election.id %>
          <%= f.submit "Hlasovat", {:class => 'btn btn-primary pull-right'} %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/ballot_papers/_form.html.erb
<%= form_for(ballot_paper) do |f| %>
  <% if ballot_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_paper.errors.count, "error") %> prohibited this ballot_paper from being saved:</h2>

      <ul>
      <% ballot_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vote %>
    <%= f.text_field :vote %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballot_papers/_resolution_form.html.erb
<%= form_for(ballot_paper) do |f| %>
  <% if ballot_paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ballot_paper.errors.count, "error") %> prohibited this ballot_paper from being saved:</h2>

      <ul>
      <% ballot_paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="2">Hlasujete PRO/PROTI usnesení?</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= radio_button_tag "choices[resolution]", "for", true %> PRO</td>
        <td><%= radio_button_tag "choices[resolution]", "against" %> PROTI</td>
      </tr>
      <tr>
        <td colspan="2">
          <%= hidden_field_tag "election", @election.id %>
          <%= f.submit "Hlasovat", {:class => 'btn btn-primary pull-right'} %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/ballot_papers/edit.html.erb
<h1>Editing Ballot Paper</h1>

<%= render 'form', ballot_paper: @ballot_paper %>

<%= link_to 'Show', @ballot_paper %> |
<%= link_to 'Back', ballot_papers_path %>

app/views/ballot_papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ballot Papers</h1>

<table>
  <thead>
    <tr>
      <th>Vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ballot_papers.each do |ballot_paper| %>
      <tr>
        <td><%= ballot_paper.vote %></td>
        <td><%= link_to 'Show', ballot_paper %></td>
        <td><%= link_to 'Edit', edit_ballot_paper_path(ballot_paper) %></td>
        <td><%= link_to 'Destroy', ballot_paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ballot Paper', new_ballot_paper_path %>

app/views/ballot_papers/new.html.erb
<h1>Hlasovací lístek - <%= @election.title %></h1>

<% if !@election.is_voting_phase? then %>
    <div class="alert alert-warning">
        Nemůžete hlasovat
    </div>
<% else %>
    <p>
        <strong>Popis voleb:</strong>
        <%= @election.description %>
    </p>

    <% if @election.counting_rules == 'resolution' %>
        <%= render "resolution_form", { ballot_paper: @ballot_paper, election: @election } %>
    <% end %>

    <% if @election.counting_rules == 'candidates_approval' %>
        <%= render "candidates_approval_form", { ballot_paper: @ballot_paper, election: @election } %>
    <% end %>

    <% if @election.counting_rules == 'candidates_choosing' %>
        <%= render "candidates_choosing_form", { ballot_paper: @ballot_paper, election: @election } %>
    <% end %>
<% end %>

app/views/ballot_papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vote:</strong>
  <%= @ballot_paper.vote %>
</p>

<%= link_to 'Edit', edit_ballot_paper_path(@ballot_paper) %> |
<%= link_to 'Back', ballot_papers_path %>