config/routes.rb
Rails.application.routes.draw do
  resources :election_protocols
  resources :candidate_lists
  resources :ballot_boxes
  resources :ballot_papers
  resources :candidates
  resources :elections
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq'

  root 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/destroy'
  
  post '/candidate_lists/:id/submit_candidacy', to: 'candidate_lists#submit_candidacy'
  delete '/candidate_lists/:id/destroy_candidacy/:candidate_id', to: 'candidate_lists#destroy_candidacy'

  get 'elections/:id/count_votes', to: 'elections#count_votes'
  post 'elections/:id/count_votes', to: 'elections#count_votes'

end

app/models/candidate_list.rb
class CandidateList
  include Mongoid::Document
  belongs_to :election
  embeds_many :candidates
end

app/controllers/candidate_lists_controller.rb
class CandidateListsController < ApplicationController
  before_action :set_candidate_list, only: [:show, :edit, :update, :destroy, :submit_candidacy, :destroy_candidacy]

  # GET /candidate_lists
  # GET /candidate_lists.json
  def index
    @candidate_lists = CandidateList.all
  end

  # GET /candidate_lists/1
  # GET /candidate_lists/1.json
  def show
    if @candidate_list.nil? || @candidate_list.election.nil? || @candidate_list.election.is_election_type_resolution?
      not_found
    else
      @candidates = @candidate_list.candidates
    end
  end

  # GET /candidate_lists/new
  def new
    @candidate_list = CandidateList.new
  end

  # GET /candidate_lists/1/edit
  def edit
  end

  # POST /candidate_lists
  # POST /candidate_lists.json
  def create
    @candidate_list = CandidateList.new(candidate_list_params)

    respond_to do |format|
      if @candidate_list.save
        format.html { redirect_to @candidate_list, notice: 'Candidate list was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_list }
      else
        format.html { render :new }
        format.json { render json: @candidate_list.errors, status: :unprocessable_entity }
      end
    end
  end

  #POST /candidate_lists/1/submit_candidacy
  def submit_candidacy
    authorize! :submit_candidacy, @candidate_list
    user = current_user['party_registry_profile']
    @candidate_list.candidates.build(:id_person_party_registry => user['id'], :first_name => user['first_name'], :last_name => user['last_name'])
    @candidate_list.save
    respond_to do |format|
      format.html { redirect_to @candidate_list, notice: 'Vaše podání kandidatury bylo zaznamenáno.'}
      format.json { render :show, location: @candidate_list }
    end
  end

  #DELETE /candidate_lists/:id/destroy_candidacy/:candidate.id
  def destroy_candidacy
    authorize! :destroy_candidacy, @candidate_list
    candidate = @candidate_list.candidates.find(params[:candidate_id])
    candidate.destroy
    respond_to do |format|
      format.html { redirect_to @candidate_list, notice: 'Kandidát byl odstraněn.'}
      format.json { render :show, location: @candidate_list }
    end
  end

  # PATCH/PUT /candidate_lists/1
  # PATCH/PUT /candidate_lists/1.json
  def update
    respond_to do |format|
      if @candidate_list.update(candidate_list_params)
        format.html { redirect_to @candidate_list, notice: 'Candidate list was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_list }
      else
        format.html { render :edit }
        format.json { render json: @candidate_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_lists/1
  # DELETE /candidate_lists/1.json
  def destroy
    @candidate_list.destroy
    respond_to do |format|
      format.html { redirect_to candidate_lists_url, notice: 'Candidate list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate_list
      @candidate_list = CandidateList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_list_params
      params.fetch(:candidate_list, {})
    end
end

app/helpers/candidate_lists_helper.rb
module CandidateListsHelper
end

app/views/candidate_lists/_form.html.erb
<%= form_for(candidate_list) do |f| %>
  <% if candidate_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate_list.errors.count, "error") %> prohibited this candidate_list from being saved:</h2>

      <ul>
      <% candidate_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidate_lists/edit.html.erb
<h1>Editing Candidate List</h1>

<%= render 'form', candidate_list: @candidate_list %>

<%= link_to 'Show', @candidate_list %> |
<%= link_to 'Back', candidate_lists_path %>

app/views/candidate_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidate Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidate_lists.each do |candidate_list| %>
      <tr>
        <td><%= link_to 'Show', candidate_list %></td>
        <td><%= link_to 'Edit', edit_candidate_list_path(candidate_list) %></td>
        <td><%= link_to 'Destroy', candidate_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate List', new_candidate_list_path %>

app/views/candidate_lists/new.html.erb
<h1>New Candidate List</h1>

<%= render 'form', candidate_list: @candidate_list %>

<%= link_to 'Back', candidate_lists_path %>

app/views/candidate_lists/show.html.erb
<h1>Kandidátní listina - <%= @candidate_list.election.title %></h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Jméno</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.full_name %></td>
        <td>
          <% if @candidate_list.election.state == 'preparation' %>
            <% if can? :destroy_candidacy, @candidate_list %>
              <%= link_to 'Zrušit kandidaturu', candidate_list_path+'/destroy_candidacy/'+candidate.id, { method: :delete, data: { confirm: 'Opravdu chcete odebrat kandidáta ?' }, :class => 'btn btn-primary pull-right'}  %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end.empty? %>
      <tr>
        <td colspan="2" class="info">
          Zatím se nepřihlásil žádný kandidát.
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<% if @candidate_list.election.state == 'preparation' then %>
  <% if can? :submit_candidacy, @candidate_list %>
    <%= link_to 'Podat kandidaturu', candidate_list_path+'/submit_candidacy', { method: :post, 
  data: { confirm: 'Jste si jistí, že chcete podat kandidaturu ?' }, :class => 'btn btn-primary'}  %>
  <% end %>
<% end %>